//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEvent
    {
        public int id { get; set; }
        public string title { get; set; }
        public bool allDay { get; set; }
        public string description { get; set; }
        public Nullable<int> recurranceType { get; set; }
        public bool showInCal { get; set; }
        public bool showOnHome { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public string url { get; set; }
        public bool cancelled { get; set; }
        public string createdBy { get; set; }
        public Nullable<int> imgId { get; set; }
        public Nullable<int> recurranceRef { get; set; }
    }
}
